### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by octplane** [octplane/photo-map#1]
- [x] scan pictures and extract GPS information
- [ ] poc static file + websocket server
- [ ] create web server with WebSocket, stream parsing to connected client
- [ ] create simple Web app that display the data on a map
- [ ] scan pictures and extract time/date information
- [ ] infer missing GPS data from neighbour images (filename / datetime based)
- [ ] extend geo information with a Geoname
